# Generated by Django 5.0.1 on 2024-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='tag',
            field=models.CharField(default='sem tag', max_length=100),
        ),
    ]
